name: OasisPixelGyms
main: com.gmail.madscientist032.OasisPixelGyms.OasisPixelGyms
version: Alpha Build 073114 Rev 01
description: Oasis Pixelmon Gym Stuff
author: madscientist032
commands:

  leaders:
    description: Lists online Gym Leaders!
    usage: "Usage: /<command>"
    aliases: [listleaders]
    permission: oasispixelgyms.leaders.list
    permission-message: You don't have permissions for <permission>

permissions:
    oasispixelgyms.leaders.list:
        description: Shows a list online Gym Leaders!

    oasispixelgyms.gym.leader:
        description: Grants Gym leader access!

    oasispixelgyms.gym.coleader:
        description: Grants Gym Co-leader access!
    
    oasispixelgyms.staff:
        description: Disables join notification for staff leaders!
    
    oasispixelgyms.gyms.leader.grass:
        description: Indicates the grass gym leaders!

    oasispixelgyms.gyms.leader.flying:
        description: Indicates the flying gym leaders!

    oasispixelgyms.gyms.leader.bug:
        description: Indicates the bug gym leaders!

    oasispixelgyms.gyms.leader.psychic:
        description: Indicates the psychic gym leaders!

    oasispixelgyms.gyms.leader.water:
        description: Indicates the water gym leaders!

    oasispixelgyms.gyms.leader.steel:
        description: Indicates the steel gym leaders!

    oasispixelgyms.gyms.leader.dragon:
        description: Indicates the dragon gym leaders!

    oasispixelgyms.gyms.leader.fire:
        description: Indicates the fire gym leaders!

