name: OasisPixelGyms
main: com.gmail.madscientist032.OasisPixelGyms.OasisPixelGyms
version: OasisPixelGyms Alpha Build 062514
description: Oasis Pixelmon Gym Stuff
author: madscientist032
commands:

  leaders:
    description: Lists online Gym Leaders!
    usage: "Usage: /<command>"
    aliases: [leadersonline]
    permission: OasisPixelGym.leaders.list
    permission-message: You don't have permissions for <permission>

permissions:
    OasisPixelGym.leaders.list:
        description: Shows a list online Gym Leaders!

    OasisPixelGym.gym.leader:
        description: Grants Gym leader access!

    OasisPixelGym.gym.coleader:
        description: Grants Gym Co-leader access!