name: OasisPixelGyms
main: com.gmail.madscientist032.OasisPixelGyms.OasisPixelGyms
version: Alpha Build 062514 Rev 11
description: Oasis Pixelmon Gym Stuff
author: madscientist032
commands:

  leaders:
    description: Lists online Gym Leaders!
    usage: "Usage: /<command>"
    aliases: [listleaders]
    permission: oasispixelgyms.leaders.list
    permission-message: You don't have permissions for <permission>

permissions:
    oasispixelgyms.leaders.list:
        description: Shows a list online Gym Leaders!

    oasispixelgyms.gym.leader:
        description: Grants Gym leader access!

    oasispixelgyms.gym.coleader:
        description: Grants Gym Co-leader access!